# Working with Dates and Time in Pandas DataFrame

In [102]:
import pandas as pd
import numpy as np

Pandas was developed in the context of financial modeling, so as you might expect, it contains a fairly extensive set of tools for working with dates, times, and time-indexed data.
Date and time data comes in a few flavors, which we will discuss here:

- *Time stamps* reference particular moments in time (e.g., July 4th, 2015 at 7:00am).  

- *Time intervals* and *periods* reference a length of time between a particular beginning and end point; for example, the year 2015. Periods usually reference a special case of time intervals in which each interval is of uniform length and does not overlap (e.g., 24 hour-long periods comprising days).
- *Time deltas* or *durations* reference an exact length of time (e.g., a duration of 22.56 seconds).

In this section, we will introduce how to work with each of these types of date/time data in Pandas.
This short section is by no means a complete guide to the time series tools available in Python or Pandas, but instead is intended as a broad overview of how you as a user should approach working with time series.  

We will start with a brief discussion of tools for dealing with dates and times in Python, before moving more specifically to a discussion of the tools provided by Pandas.
After listing some resources that go into more depth, we will review some short examples of working with time series data in Pandas.

## 1. Dates and Times in Python

The Python world has a number of available representations of dates, times, deltas, and timespans.
While the time series tools provided by Pandas tend to be the most useful for data science applications, it is helpful to see their relationship to other packages used in Python.

### Native Python dates and times: ``datetime`` and ``dateutil``

Python's basic objects for working with dates and times reside in the built-in ``datetime`` module.
Along with the third-party ``dateutil`` module, you can use it to quickly perform a host of useful functionalities on dates and times.
For example, you can manually build a date using the ``datetime`` type:

In [103]:
from datetime import datetime
datetime(year = 2015, month = 7, day = 4)

datetime.datetime(2015, 7, 4, 0, 0)

Or, using the ``dateutil`` module, you can parse dates from a variety of string formats:

In [104]:
# https://dateutil.readthedocs.io/en/stable/parser.html#functions
from dateutil import parser
print(parser.parse("4th of July, 2015"))
print(parser.parse("07/04/2015"))
print(parser.parse("07/04/2015", dayfirst=True))

2015-07-04 00:00:00
2015-07-04 00:00:00
2015-04-07 00:00:00

In [105]:
print(parser.parse("7/4/2015"))
print(parser.parse("07-04-2015"))
print(parser.parse("2015-07-04"))

2015-07-04 00:00:00
2015-07-04 00:00:00
2015-07-04 00:00:00

Once you have a ``datetime`` object, you can do things like printing the day of the week:

In [106]:
# https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior
datetime(year = 2025, month = 4, day = 2).strftime('%A')

'Wednesday'

In the final line, we've used one of the standard string format codes for printing dates (``"%A"``), which you can read about in the [strftime section](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior) of Python's [datetime documentation](https://docs.python.org/3/library/datetime.html).
Documentation of other useful date utilities can be found in [dateutil's online documentation](http://labix.org/python-dateutil).
A related package to be aware of is [``pytz``](http://pytz.sourceforge.net/), which contains tools for working with the most migrane-inducing piece of time series data: time zones.

The power of ``datetime`` and ``dateutil`` lie in their flexibility and easy syntax: you can use these objects and their built-in methods to easily perform nearly any operation you might be interested in.
Where they break down is when you wish to work with large arrays of dates and times:
just as lists of Python numerical variables are suboptimal compared to NumPy-style typed numerical arrays, lists of Python datetime objects are suboptimal compared to typed arrays of encoded dates.

### Typed arrays of times: NumPy's ``datetime64``

The weaknesses of Python's datetime format inspired the NumPy team to add a set of native time series data type to NumPy.
The ``datetime64`` dtype encodes dates as 64-bit integers, and thus allows arrays of dates to be represented very compactly.
The ``datetime64`` requires a very specific input format:

In [107]:
import numpy as np
date = np.array('2015-07-04', dtype = np.datetime64)
date

array('2015-07-04', dtype='datetime64[D]')

In [108]:
np.array('07-04-2015', dtype = np.datetime64)
# Fails on purpose: NumPy only accepts ISO format (AAAA-MM-DD)

ValueError: Cannot create a NumPy datetime other than NaT with generic units

Once we have this date formatted, however, we can quickly do vectorized operations on it:

In [ ]:
date

array('2015-07-04', dtype='datetime64[D]')

In [ ]:
dates = date + np.arange(12)
dates

array(['2015-07-04', '2015-07-05', '2015-07-06', '2015-07-07',
       '2015-07-08', '2015-07-09', '2015-07-10', '2015-07-11',
       '2015-07-12', '2015-07-13', '2015-07-14', '2015-07-15'],
      dtype='datetime64[D]')

Because of the uniform type in NumPy ``datetime64`` arrays, this type of operation can be accomplished much more quickly than if we were working directly with Python's ``datetime`` objects, especially as arrays get large
(we introduced this type of vectorization in [Computation on NumPy Arrays: Universal Functions](02.03-Computation-on-arrays-ufuncs.ipynb)).

One detail of the ``datetime64`` and ``timedelta64`` objects is that they are built on a *fundamental time unit*.
Because the ``datetime64`` object is limited to 64-bit precision, the range of encodable times is $2^{64}$ times this fundamental unit.
In other words, ``datetime64`` imposes a trade-off between *time resolution* and *maximum time span*.

For example, if you want a time resolution of one nanosecond, you only have enough information to encode a range of $2^{64}$ nanoseconds, or just under 600 years.
NumPy will infer the desired unit from the input; for example, here is a day-based datetime:

In [ ]:
np.datetime64('2015-07-04')

numpy.datetime64('2015-07-04')

Here is a minute-based datetime:

In [ ]:
np.datetime64('2015-07-04 12:00:30')

numpy.datetime64('2015-07-04T12:00:30')

Notice that the time zone is automatically set to the local time on the computer executing the code.
You can force any desired fundamental unit using one of many format codes; for example, here we'll force a nanosecond-based time:

In [ ]:
np.datetime64('2015-07-04 12:59:59.50', 'ns')

numpy.datetime64('2015-07-04T12:59:59.500000000')

The following table, drawn from the [NumPy datetime64 documentation](http://docs.scipy.org/doc/numpy/reference/arrays.datetime.html), lists the available format codes along with the relative and absolute timespans that they can encode:

|Code    | Meaning     | Time span (relative) | Time span (absolute)   |
|--------|-------------|----------------------|------------------------|
| ``Y``  | Year	       | ± 9.2e18 years       | [9.2e18 BC, 9.2e18 AD] |
| ``M``  | Month       | ± 7.6e17 years       | [7.6e17 BC, 7.6e17 AD] |
| ``W``  | Week	       | ± 1.7e17 years       | [1.7e17 BC, 1.7e17 AD] |
| ``D``  | Day         | ± 2.5e16 years       | [2.5e16 BC, 2.5e16 AD] |
| ``h``  | Hour        | ± 1.0e15 years       | [1.0e15 BC, 1.0e15 AD] |
| ``m``  | Minute      | ± 1.7e13 years       | [1.7e13 BC, 1.7e13 AD] |
| ``s``  | Second      | ± 2.9e12 years       | [ 2.9e9 BC, 2.9e9 AD]  |
| ``ms`` | Millisecond | ± 2.9e9 years        | [ 2.9e6 BC, 2.9e6 AD]  |
| ``us`` | Microsecond | ± 2.9e6 years        | [290301 BC, 294241 AD] |
| ``ns`` | Nanosecond  | ± 292 years          | [ 1678 AD, 2262 AD]    |
| ``ps`` | Picosecond  | ± 106 days           | [ 1969 AD, 1970 AD]    |
| ``fs`` | Femtosecond | ± 2.6 hours          | [ 1969 AD, 1970 AD]    |
| ``as`` | Attosecond  | ± 9.2 seconds        | [ 1969 AD, 1970 AD]    |

### 3. Dates and Times in Pandas

#### Default arguments

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({'date': ['3/10/2000', '3/11/2000', '3/12/2000'],
                   'value': [2, 3, 4]})
df

        date  value
0  3/10/2000      2
1  3/11/2000      3
2  3/12/2000      4

In [ ]:
df.dtypes

date       str
value    int64
dtype: object

In [ ]:
df['date'] = pd.to_datetime(df['date']) # dayfirst = False
df

        date  value
0 2000-03-10      2
1 2000-03-11      3
2 2000-03-12      4

In [ ]:
df.dtypes

date     datetime64[us]
value             int64
dtype: object

#### Day first format

In [ ]:
df = pd.DataFrame({'date': ['3/10/2000', '3/11/2000', '3/12/2000'],
                   'value': [2, 3, 4]})

df['date'] = pd.to_datetime(df['date'], dayfirst=True)
df

        date  value
0 2000-10-03      2
1 2000-11-03      3
2 2000-12-03      4

#### Custom format

In [ ]:
df = pd.DataFrame({'date': ['2016-6-10 20:30:0', 
                            '2016-7-1 19:45:30', 
                            '2013-10-12 4:5:1'],
                   'value': [2, 3, 4]})

df['date'] = pd.to_datetime(df['date'], format="%Y-%m-%d %H:%M:%S")
df

                 date  value
0 2016-06-10 20:30:00      2
1 2016-07-01 19:45:30      3
2 2013-10-12 04:05:01      4

#### Handle parsing error

In [ ]:
df = pd.DataFrame({'date': ['3/10/2000', 'a/11/2000', '3/12/2000'],
                   'value': [2, 3, 4]})

# Esta celda falla a propósito: 'a/11/2000' no es una fecha válida
# pandas 3 ya no admite errors='ignore'.
df['date'] = pd.to_datetime(df['date'])

ValueError: time data "a/11/2000" doesn't match format "%m/%d/%Y". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [112]:
df = pd.DataFrame({'date': ['3/10/2000', 'a/11/2000', '3/12/2000'],
                   'value': [2, 3, 4]})

df['date'] = pd.to_datetime(df['date'], errors = 'coerce')
df

        date  value
0 2000-03-10      2
1        NaT      3
2 2000-03-12      4

In [113]:
df[df['date'].isnull()]

  date  value
1  NaT      3

In [114]:
df.dtypes

date     datetime64[us]
value             int64
dtype: object

In [115]:
print(df.at[0, 'date'])
print(df.at[1, 'date'])

2000-03-10 00:00:00
NaT

### 4. Assemble a datetime from multiple columns

In [116]:
df = pd.DataFrame({'year': [2015, 2016],
                   'month': [2, 3],
                   'day': [4, 5]})

df

   year  month  day
0  2015      2    4
1  2016      3    5

In [117]:
df.dtypes

year     int64
month    int64
day      int64
dtype: object

In [118]:
df['date'] = pd.to_datetime(df)

In [119]:
df

   year  month  day       date
0  2015      2    4 2015-02-04
1  2016      3    5 2016-03-05

In [120]:
df.dtypes

year              int64
month             int64
day               int64
date     datetime64[us]
dtype: object

### 5. Get year, month and day

In [121]:
df = pd.DataFrame({'name': ['Tom', 'Andy', 'Lucas'],
                 'DoB': ['08-05-1997', '04-28-1996', '12-16-1995']})

df['DoB'] = pd.to_datetime(df['DoB'])
df

    name        DoB
0    Tom 1997-08-05
1   Andy 1996-04-28
2  Lucas 1995-12-16

In [122]:
df['year'] = df['DoB'].dt.year
df['month'] = df['DoB'].dt.month
df['day'] = df['DoB'].dt.day
df

    name        DoB  year  month  day
0    Tom 1997-08-05  1997      8    5
1   Andy 1996-04-28  1996      4   28
2  Lucas 1995-12-16  1995     12   16

In [123]:
df.dtypes

name                str
DoB      datetime64[us]
year              int32
month             int32
day               int32
dtype: object

### 6. Get the week of year, the day of week and leap year

In [124]:
df['week_of_year'] = df['DoB'].dt.isocalendar().week
df['day_of_week'] = df['DoB'].dt.dayofweek
df['is_leap_year'] = df['DoB'].dt.is_leap_year
df

    name        DoB  year  month  day  week_of_year  day_of_week  is_leap_year
0    Tom 1997-08-05  1997      8    5            32            1         False
1   Andy 1996-04-28  1996      4   28            17            6          True
2  Lucas 1995-12-16  1995     12   16            50            5         False

In [125]:
dw_mapping={
    0: 'Monday', 
    1: 'Tuesday', 
    2: 'Wednesday', 
    3: 'Thursday', 
    4: 'Friday',
    5: 'Saturday', 
    6: 'Sunday'
}

df['day_of_week_name']=df['DoB'].dt.weekday.map(dw_mapping)
df

,name,DoB,year,month,day,week_of_year,day_of_week,is_leap_year,day_of_week_name
0,Tom,1997-08-05,1997,8,5,32,1,False,Tuesday
1,Andy,1996-04-28,1996,4,28,17,6,True,Sunday
2,Lucas,1995-12-16,1995,12,16,50,5,False,Saturday

### 7. Get the age from the date of birth

In [126]:
pd.to_datetime('today')

Timestamp('2026-10-08 13:47:32.059987')

In [127]:
datetime.today()

datetime.datetime(2026, 10, 8, 13, 47, 33, 464812)

In [128]:
today = pd.to_datetime('today')
(today - df['DoB'])

0   10656 days 13:48:02.898495
1   11120 days 13:48:02.898495
2   11254 days 13:48:02.898495
Name: DoB, dtype: timedelta64[us]

In [41]:
today = pd.to_datetime('today')
df['age'] = (today - df['DoB']).dt.days//365.25

df

,name,DoB,year,month,day,week_of_year,day_of_week,is_leap_year,day_of_week_name,age
0,Tom,1997-08-05,1997,8,5,32,1,False,Tuesday,29.0
1,Andy,1996-04-28,1996,4,28,17,6,True,Sunday,30.0
2,Lucas,1995-12-16,1995,12,16,50,5,False,Saturday,30.0

### 8. Improve performance by setting date column as the index

In [42]:
df = pd.read_csv('data/city_sales.csv', parse_dates = ['date'])
df

                       date  num       city
0       2015-01-01 09:00:00    4     London
1       2015-01-01 09:01:00    4     London
2       2015-01-01 09:02:00    3     London
3       2015-01-01 09:03:00    3     London
4       2015-01-01 09:04:00    3     London
...                     ...  ...        ...
1795139 2019-01-31 15:56:00    3  Cambridge
1795140 2019-01-31 15:57:00    3  Cambridge
1795141 2019-01-31 15:58:00    3  Cambridge
1795142 2019-01-31 15:59:00    3  Cambridge
1795143 2019-01-31 16:00:00    2  Cambridge

[1795144 rows x 3 columns]

In [43]:
df.describe(include='all')

                              date           num     city
count                      1795144  1.795144e+06  1795144
unique                         NaN           NaN        4
top                            NaN           NaN   London
freq                           NaN           NaN   448786
mean    2017-01-16 10:05:27.579738  2.801503e+00      NaN
min            2015-01-01 09:00:00  1.000000e+00      NaN
25%            2016-01-08 12:30:00  2.000000e+00      NaN
50%            2017-01-17 00:30:00  3.000000e+00      NaN
75%            2018-01-24 12:30:00  3.000000e+00      NaN
max            2019-01-31 16:00:00  4.000000e+00      NaN
std                            NaN  8.714650e-01      NaN

In [44]:
4*448786

1795144

In [45]:
df.dtypes

date    datetime64[us]
num              int64
city               str
dtype: object

In [46]:
df = pd.read_csv('data/city_sales.csv', parse_dates = ['date'])
df.set_index(['date'], inplace=True)
df.head()

                     num    city
date
2015-01-01 09:00:00    4  London
2015-01-01 09:01:00    4  London
2015-01-01 09:02:00    3  London
2015-01-01 09:03:00    3  London
2015-01-01 09:04:00    3  London

In [47]:
df = pd.read_csv('data/city_sales.csv', parse_dates = ['date'], index_col = 'date')
df.head()

                     num    city
date
2015-01-01 09:00:00    4  London
2015-01-01 09:01:00    4  London
2015-01-01 09:02:00    3  London
2015-01-01 09:03:00    3  London
2015-01-01 09:04:00    3  London

In [48]:
# Tenemos un DateTimeIndex
df.index

DatetimeIndex(['2015-01-01 09:00:00', '2015-01-01 09:01:00',
               '2015-01-01 09:02:00', '2015-01-01 09:03:00',
               '2015-01-01 09:04:00', '2015-01-01 09:05:00',
               '2015-01-01 09:06:00', '2015-01-01 09:07:00',
               '2015-01-01 09:08:00', '2015-01-01 09:09:00',
               ...
               '2019-01-31 15:51:00', '2019-01-31 15:52:00',
               '2019-01-31 15:53:00', '2019-01-31 15:54:00',
               '2019-01-31 15:55:00', '2019-01-31 15:56:00',
               '2019-01-31 15:57:00', '2019-01-31 15:58:00',
               '2019-01-31 15:59:00', '2019-01-31 16:00:00'],
              dtype='datetime64[us]', name='date', length=1795144, freq=None)

In [49]:
from datetime import datetime
dates = pd.to_datetime([datetime(2015, 7, 3), '4th of July, 2015',
                       '2015-Jul-6', '07-07-2015', '20150708'])
dates

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-06', '2015-07-07',
               '2015-07-08'],
              dtype='datetime64[us]', freq=None)

### 9. Select data with a specific year and perform aggregation

In [50]:
df.loc['2018']

                     num       city
date
2018-01-01 09:00:00    2     London
2018-01-01 09:01:00    1     London
2018-01-01 09:02:00    3     London
2018-01-01 09:03:00    3     London
2018-01-01 09:04:00    3     London
...                  ...        ...
2018-12-31 15:56:00    4  Cambridge
2018-12-31 15:57:00    2  Cambridge
2018-12-31 15:58:00    3  Cambridge
2018-12-31 15:59:00    3  Cambridge
2018-12-31 16:00:00    2  Cambridge

[439524 rows x 2 columns]

In [51]:
df.loc['2018', 'num'].head()

date
2018-01-01 09:00:00    2
2018-01-01 09:01:00    1
2018-01-01 09:02:00    3
2018-01-01 09:03:00    3
2018-01-01 09:04:00    3
Name: num, dtype: int64

In [52]:
df.loc['2018'].groupby('city').sum()

              num
city
Cambridge  308428
Durham     307965
London     307431
Oxford     307366

### 10. Select data with a specific month or a specific day of the month

In [53]:
df.loc['2018-5'].head()

                     num    city
date
2018-05-01 09:00:00    1  London
2018-05-01 09:01:00    4  London
2018-05-01 09:02:00    3  London
2018-05-01 09:03:00    2  London
2018-05-01 09:04:00    3  London

In [54]:
df.loc['2018-5-1'].head()

                     num    city
date
2018-05-01 09:00:00    1  London
2018-05-01 09:01:00    4  London
2018-05-01 09:02:00    3  London
2018-05-01 09:03:00    2  London
2018-05-01 09:04:00    3  London

In [55]:
cond = df.index.month == 2
df[cond].head()

                     num    city
date
2015-02-02 09:00:00    4  London
2015-02-02 09:01:00    3  London
2015-02-02 09:02:00    3  London
2015-02-02 09:03:00    2  London
2015-02-02 09:04:00    1  London

### 11. Select data between two dates

In [56]:
# El slicing por rango de fechas exige un índice ordenado
# (con el índice desordenado, pandas 3 lanza KeyError)
df = df.sort_index()
df.loc['2016':'2018']

                     num       city
date
2016-01-01 09:00:00    3  Cambridge
2016-01-01 09:00:00    4     London
2016-01-01 09:00:00    3     Durham
2016-01-01 09:00:00    3     Oxford
2016-01-01 09:01:00    2     Oxford
...                  ...        ...
2018-12-31 15:59:00    2     Oxford
2018-12-31 16:00:00    2     Durham
2018-12-31 16:00:00    3     Oxford
2018-12-31 16:00:00    2  Cambridge
2018-12-31 16:00:00    3     London

[1316888 rows x 2 columns]

In [57]:
df.loc['2018-5-2 10' : '2018-5-2 11' ]

                     num       city
date
2018-05-02 10:00:00    3  Cambridge
2018-05-02 10:00:00    3     Oxford
2018-05-02 10:00:00    3     Durham
2018-05-02 10:00:00    2     London
2018-05-02 10:01:00    3     London
...                  ...        ...
2018-05-02 11:58:00    4  Cambridge
2018-05-02 11:59:00    3     Durham
2018-05-02 11:59:00    1  Cambridge
2018-05-02 11:59:00    4     London
2018-05-02 11:59:00    3     Oxford

[480 rows x 2 columns]

In [58]:
df.loc['2018-5-2 10:30' : '2018-5-2 10:45' ]

                     num       city
date
2018-05-02 10:30:00    3     London
2018-05-02 10:30:00    3     Oxford
2018-05-02 10:30:00    2     Durham
2018-05-02 10:30:00    3  Cambridge
2018-05-02 10:31:00    2     Durham
...                  ...        ...
2018-05-02 10:44:00    3  Cambridge
2018-05-02 10:45:00    4     London
2018-05-02 10:45:00    3     Durham
2018-05-02 10:45:00    3     Oxford
2018-05-02 10:45:00    1  Cambridge

[64 rows x 2 columns]

In [59]:
df.between_time('10:30','10:45')

                     num       city
date
2015-01-01 10:30:00    4     London
2015-01-01 10:30:00    4  Cambridge
2015-01-01 10:30:00    4     Oxford
2015-01-01 10:30:00    2     Durham
2015-01-01 10:31:00    3     London
...                  ...        ...
2019-01-31 10:44:00    2     London
2019-01-31 10:45:00    4     London
2019-01-31 10:45:00    4  Cambridge
2019-01-31 10:45:00    3     Oxford
2019-01-31 10:45:00    2     Durham

[68224 rows x 2 columns]

In [60]:
df.shape

(1795144, 2)

### 12. Operations with dates

In [61]:
df = pd.DataFrame({'name': ['Tom', 'Andy', 'Lucas'],
                 'DoB': ['08-05-1997', '04-28-1996', '12-16-1995']})

df['DoB'] = pd.to_datetime(df['DoB'])
df

    name        DoB
0    Tom 1997-08-05
1   Andy 1996-04-28
2  Lucas 1995-12-16

In [62]:
from pandas.tseries.offsets import DateOffset, BDay

print(df['DoB'] + DateOffset(days = 5))
print(df['DoB'] + DateOffset(days = -5))
print(df['DoB'] + DateOffset(months = 5))

0   1997-08-10
1   1996-05-03
2   1995-12-21
Name: DoB, dtype: datetime64[us]
0   1997-07-31
1   1996-04-23
2   1995-12-11
Name: DoB, dtype: datetime64[us]
0   1998-01-05
1   1996-09-28
2   1996-05-16
Name: DoB, dtype: datetime64[us]

In [63]:
BDay(10)

In [64]:
print(df['DoB'])
print(df['DoB'] + BDay(10))

0   1997-08-05
1   1996-04-28
2   1995-12-16
Name: DoB, dtype: datetime64[us]
0   1997-08-19
1   1996-05-10
2   1995-12-29
Name: DoB, dtype: datetime64[us]

In [65]:
df['DoB+10BD'] = df['DoB'] + BDay(10)
df

    name        DoB   DoB+10BD
0    Tom 1997-08-05 1997-08-19
1   Andy 1996-04-28 1996-05-10
2  Lucas 1995-12-16 1995-12-29

In [66]:
df['date_diff'] = (df['DoB+10BD'] - df['DoB']).dt.days
df

    name        DoB   DoB+10BD  date_diff
0    Tom 1997-08-05 1997-08-19         14
1   Andy 1996-04-28 1996-05-10         12
2  Lucas 1995-12-16 1995-12-29         13

In [67]:
df.dtypes

name                    str
DoB          datetime64[us]
DoB+10BD     datetime64[us]
date_diff             int64
dtype: object

### 13. Regular sequences: ``pd.date_range()``

To make the creation of **regular date** sequences more convenient, Pandas offers a few functions for this purpose: ``pd.date_range()`` for timestamps, ``pd.period_range()`` for periods, and ``pd.timedelta_range()`` for time deltas.
We've seen that **Python's ``range()`` and NumPy's ``np.arange()``** turn a startpoint, endpoint, and optional stepsize into a sequence.
Similarly, ``pd.date_range()`` accepts a start date, an end date, and an optional frequency code to create a regular sequence of dates.
By default, the frequency is one day:

In [68]:
pd.date_range('2015-07-03', '2015-07-10')

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[us]', freq='D')

Alternatively, the date range can be specified not with a start and endpoint, but with a startpoint and a number of periods:

In [69]:
pd.date_range('2015-07-03', periods = 8)

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[us]', freq='D')

The spacing can be modified by altering the ``freq`` argument, which defaults to ``D``.
For example, here we will construct a range of hourly timestamps:

In [70]:
pd.date_range('2015-01-01', periods = 12, freq='MS')

DatetimeIndex(['2015-01-01', '2015-02-01', '2015-03-01', '2015-04-01',
               '2015-05-01', '2015-06-01', '2015-07-01', '2015-08-01',
               '2015-09-01', '2015-10-01', '2015-11-01', '2015-12-01'],
              dtype='datetime64[us]', freq='MS')

### 14. Handle missing values

In [71]:
# Creamos algunos missings aposta con la rolling window
df = pd.read_csv('data/city_sales.csv', parse_dates=['date'], index_col='date')
df

                     num       city
date
2015-01-01 09:00:00    4     London
2015-01-01 09:01:00    4     London
2015-01-01 09:02:00    3     London
2015-01-01 09:03:00    3     London
2015-01-01 09:04:00    3     London
...                  ...        ...
2019-01-31 15:56:00    3  Cambridge
2019-01-31 15:57:00    3  Cambridge
2019-01-31 15:58:00    3  Cambridge
2019-01-31 15:59:00    3  Cambridge
2019-01-31 16:00:00    2  Cambridge

[1795144 rows x 2 columns]

In [72]:
df['rolling_sum'] = df['num'].rolling(3).mean()
df.head()

                     num    city  rolling_sum
date
2015-01-01 09:00:00    4  London          NaN
2015-01-01 09:01:00    4  London          NaN
2015-01-01 09:02:00    3  London     3.666667
2015-01-01 09:03:00    3  London     3.333333
2015-01-01 09:04:00    3  London     3.000000

In [73]:
df['rolling_sum_back'] = df['rolling_sum'].bfill()
df.head()

                     num    city  rolling_sum  rolling_sum_back
date
2015-01-01 09:00:00    4  London          NaN          3.666667
2015-01-01 09:01:00    4  London          NaN          3.666667
2015-01-01 09:02:00    3  London     3.666667          3.666667
2015-01-01 09:03:00    3  London     3.333333          3.333333
2015-01-01 09:04:00    3  London     3.000000          3.000000

In [74]:
# Creating the dataframe 
df = pd.DataFrame({"A":[12, 4, 5, None, 1],
                   "B":[None, 2, 54, 3, None],
                   "C":[20, 16, None, 3, 8],
                   "D":[14, 3, None, None, 6]})
  
# Print the dataframe
df

      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   NaN   NaN
3   NaN   3.0   3.0   NaN
4   1.0   NaN   8.0   6.0

In [75]:
df.interpolate(method = 'linear')

      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   9.5   4.0
3   3.0   3.0   3.0   5.0
4   1.0   3.0   8.0   6.0